language: objective-c
 
branches:
 only:
 - master
 
xcode_project: EasyTimer/EasyTimer.xcodeproj
xcode_scheme: EasyTimerTests
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2 
 
script:
- xcodebuild clean build test -project EasyTimer/EasyTimer.xcodeproj -scheme EasyTimerTests
