language: objective-c
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2
xcode_project: EasyTimer.xcodeproj # path to your xcodeproj folder
xcode_scheme: EasyTimerTests

before_install: 
  - sudo pip install codecov

#script: 
#- xctool clean build -project EasyTimer.xcodeproj -scheme EasyTimer CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
#- xctool test -project EasyTimer.xcodeproj -scheme EasyTimerTests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

after_success:
  - codecov
